### ISSUE TITLE
ReadMe file incorrect

### ISSUE THREAD

**Issue by AlbertoArdu** [dwertent/alias-kubectl#5]
The README.md file contains errors in the descriptions of the aliases for `kubectl get` commands.
They all start with `ke` instead of `kg`.
`ke` are also the starting characters of `kubectl edit` aliases, so this could lead to dangerous results.

**Comment by dwertent** [comment]
Thank you @AlbertoArdu for pointing this out. I guess it happened when I copy-pasted the documentation.
